apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ratings-api.fullname" . }}
  namespace: ratings
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ratings-api.name" . }}

