apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ratings-api.fullname" . }}-kv
  namespace: ratings
spec:
  provider: azure
  secretObjects:
    - secretName: ratings-runtime
      type: Opaque
      data:
        - objectName: {{ .Values.databaseSecretName | quote }}
          key: DATABASE_URL
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.workloadIdentityClientId | quote }}
    keyvaultName: {{ .Values.keyVaultName | quote }}
    tenantId: {{ .Values.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.databaseSecretName }}
          objectType: secret
