apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aks-platform
  namespace: argocd
spec:
  description: AKS platform applications controlled through GitOps
  sourceRepos:
    - "*"
  destinations:
    - namespace: ratings
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

